import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import SmoothScroll from "./components/SmoothScroll";
import CustomCursor from "./components/CustomCursor";
import { FaWhatsapp } from "react-icons/fa";
export { metadata } from "@/app/layout-metadata";

const gilroy = localFont({
  src: [
    {
      path: "../../public/fonts/gilroy/Gilroy-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/gilroy/Gilroy-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/gilroy/Gilroy-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/gilroy/Gilroy-Semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/gilroy/Gilroy-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/gilroy/Gilroy-Extrabold.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../public/fonts/gilroy/Gilroy-Black.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-gilroy",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const phoneNumber = "916357665915";

  const message =
    "Hello, I’m interested in your services and would like to discuss my project requirements with your team. Please let me know how we can proceed further.";

  return (
    <html lang="en" className={`${gilroy.variable} h-full antialiased`}>
      <head>
        <meta name="geo.region" content="IN-GJ" />
        <meta name="geo.placename" content="Ahmedabad, Gujarat, India" />
        <meta
          name="geo.position"
          content="23.05169584121351;72.51896023573782"
        />
        <meta name="ICBM" content="23.05169584121351, 72.51896023573782" />
        <meta name="language" content="English" />
        <meta name="revisit-after" content="7 days" />
        <meta name="rating" content="general" />
        <meta name="distribution" content="global" />
        <meta name="coverage" content="India" />
        <meta
          property="business:contact_data:street_address"
          content="2nd Floor, President Plaza, 5g Highway Thatej"
        />
        <meta property="business:contact_data:locality" content="Ahmedabad" />
        <meta property="business:contact_data:region" content="Gujarat" />
        <meta property="business:contact_data:postal_code" content="380054" />
        <meta property="business:contact_data:country_name" content="India" />
        <meta
          property="business:contact_data:phone_number"
          content="+91-63576-65915"
        />
        <meta
          property="business:contact_data:website"
          content="https://www.digitalsahaay.com"
        />
      </head>
      <body className="min-h-full flex flex-col bg-[#F7F7FF]">
        <SmoothScroll />

        <Header />

        {children}

        <Footer />

        {/* WhatsApp Floating Button */}
        <div className="fixed bottom-6 right-6 z-50">
          {/* Outer Pulse */}
          <span className="absolute inset-0 rounded-full bg-[#25D366] animate-ping opacity-20"></span>

          {/* Inner Pulse */}
          <span
            className="absolute inset-0 rounded-full bg-[#25D366] opacity-30"
            style={{
              animation:
                "pulse-ring 2s cubic-bezier(0.455, 0.03, 0.515, 0.955) infinite",
            }}
          ></span>

          <a
            href={`https://wa.me/${phoneNumber}?text=${encodeURIComponent(message)}`}
            target="_blank"
            rel="noopener noreferrer"
            className="relative flex items-center justify-center w-14 h-14 rounded-full bg-[#25D366] shadow-[0_10px_30px_rgba(37,211,102,0.35)] hover:scale-110 hover:shadow-[0_15px_40px_rgba(37,211,102,0.5)] transition-all duration-300"
          >
            <FaWhatsapp className="text-white text-[34px]" />
          </a>
        </div>
        <CustomCursor />
      </body>
    </html>
  );
}
